package com.utilities;

public enum Category {
	ACCESSORIES, APPAREL, ART, AUDIO, AUTOMOTIVE, BABY, BAKING, BEAUTY, BEVERAGES, BOOKS, 
    CAMPING, CANDLES, CANDY, CANNED_GOODS, CERAMICS, CLEANING, CLOTHING, COFFEE, COLLECTIBLES, COMPUTERS, 
    CONDIMENTS, COOKING, COSMETICS, CRAFTS, DAIRY, DECOR, DELI, DENTAL_CARE, DESKTOPS, DRINKWARE, ELECTRONICS, ECO_FRIENDLY,
    ESSENTIAL_OILS, FABRICS, FAMILY, FASHION, FICTION, FITNESS, FLORAL, FOOD, FOOTWEAR, FURNITURE, GADGETS, GAMES, GAMING,
    GARDEN, GIFT_CARDS, GLASSWARE, GOURMET, GROCERIES, HAIRCARE, HANDMADE, HARDWARE, HEALTH, HOBBIES, 
    HOME_GOODS, HOUSEWARES, JEWELRY, KITCHEN, KITCHENWARE, KNITWEAR, LAMPS, LEATHER_GOODS, LIGHTING, LINENS, LIQUOR, 
    MAKEUP, MEATS, MEDICAL_SUPPLIES, MOBILITY_AIDS, MUSICAL_INSTRUMENTS, NOTEBOOKS, OFFICE, OFFICE_SUPPLIES, ORGANIC, OUTDOOR, 
    PAINTINGS, PAPER_GOODS, PASTA, PATIO, PERSONAL_CARE, PETS, PHARMACY, PHOTOGRAPHY, PLANTS, PLASTICS, 
    PRINTERS, PRODUCE, RECREATIONAL, RUGS, SEAFOOD, SEASONAL, SECURITY, SHOES, SKINCARE, SNACKS, 
    SOFTWARE, SPIRITS, SPORTS, STATIONERY, TABLETS, TEA, TEXTILES, TOOLS, TOYS, TRAVEL, 
    VIDEO_GAMES, VITAMINS, WATCHES, WATER_SPORTS, WINE, WINTER, YOGA
}





